### ISSUE TITLE
Labels in percents

### ISSUE THREAD

**Issue by AlexWayfer** [kotelnik/plasma-applet-resources-monitor#4]
Do you can add config option for display labels in percents, not absolute values?

**Comment by dotancohen** [comment]
+1

**Comment by kotelnik** [comment]
Sure, next release. Thanks for suggestion.

**Comment by kotelnik** [comment]
Hi! It is done in the last commits. I'll do some other improvements and then make a new tag/release here and new version on kde-apps.

**Comment by AlexWayfer** [comment]
Hi! Thanks, it's working after restart.
